# name: Deploy Calculator

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: self-hosted

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Deploy to inactive IIS folder
#       run: |
#         $repoPath = "${{ github.workspace }}\calculator-app"  # path of checked-out code
#         $pathBlue = "C:\inetpub\wwwroot\alwaysup-blue"
#         $pathGreen = "C:\inetpub\wwwroot\alwaysup-green"
#         $pathBlueContent = Get-Content "$pathBlue\up.html"

#         if ($pathBlueContent -contains 'up') {
#             $inactiveFolder = $pathGreen
#         } else {
#             $inactiveFolder = $pathBlue
#         }

#         Write-Host "Copying latest code to $inactiveFolder"
#         Copy-Item -Path "$repoPath\*" -Destination "$inactiveFolder" -Recurse -Force

#         Write-Host "Running blue-green swap script"
#         powershell -ExecutionPolicy Bypass -File "C:\inetpub\wwwroot\switch.ps1"
